# Generated by Django 4.2 on 2023-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-id'], 'verbose_name': 'лайк', 'verbose_name_plural': 'лайки'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos', verbose_name='Аватар'),
        ),
    ]
